version: '3.2'

services:
  server1:
      build: ./spring-boot-sample-web-ui
      tty: true
      ports:
          - '8081:3000'

  server2:
      build: ./spring-boot-sample-web-ui
      tty: true
      ports:
          - '8082:3000'

  loadbalancer:
      build: ./load-balancer
      tty: true
      links:
          - server1
          - server2
      ports:
          - '80:80'

volumes:
  backend:
